### ISSUE TITLE
Is it possible to upgrade ESP8266 firmware to later AT set? If so how?

### ISSUE THREAD

**Issue by techlobo** [sbcshop/PiSquare#8]
As per https://github.com/sbcshop/PiSquare/issues/6#issuecomment-1200108046 some of the ESPRESSIF AT commands do not work (not done a full check of which ones!) - so I was curious as to whether there was a later version of the AT firmware available from AI-Thinker where these commands work, or if a later Espressif version (possibly https://github.com/espressif/esp-at/releases/tag/v2.2.1.0_esp8266) would work on this board?

If there is: please provide a link to the firmware, and what is the best method of loading it to the Pi-Square without invalidating warranty?

**Comment by sbcshop1** [comment]
No, you can not update the firmware of the esp8266 module, because, we can only access the module via the UART line.

**Comment by techlobo** [comment]
Hhmm and OTA won't work as can't access the control pins easily.
If more of these boards are to be manufactured can an updated AT firmware (that supports comms parameter configuration) be included in the esp8266 please?

**Comment by sbcshop1** [comment]
yes, we will

**Comment by techlobo** [comment]
OK thanks.

**Comment by ji03mmy18** [comment]
@TechLobo I successfully upgrade the ESP-12E firmware by using Pi Pico as a UART Bridge and manually connect GPIO0 to GND, which make ESP-12E boot into UART Mode(for flashing the firmware).

Step for flashing:
1. replace the pico firmware with uart-bridge(https://github.com/Noltari/pico-uart-bridge)
2. use serial tool (minicom, picocom or thonny) to check PC can directly communicate with ESP-12E.
3. use dupont line connect GND and GPIO0, then press the ESP RESET button on piSquare board.
4. release dupont line, use esptool.py to flash the new firmware into the ESP-12E.

If you can see the rom code when ESP-12E entering UART mode, you may see string below:
```
ets Jan  8 2013,rst cause:2, boot mode:(1,6)
```

The command that flashing the ESP-12E with esptool (have to entering UART mode first):
```shell
./esptool -p <ttyUSB or COM> --before no_reset --after hard_reset write_flash -z 0x0 <firmware.bin>
```

**Comment by misel228** [comment]
Cool, thank you!
